name: Trigger auto deployment for legal-summarizer-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/legal-summarizer-api-AutoDeployTrigger-0f895e4e-41b6-474b-b3cc-ca69e51e5311.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.LEGALSUMMARIZERAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LEGALSUMMARIZERAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LEGALSUMMARIZERAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.LEGALSUMMARIZERAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LEGALSUMMARIZERAPI_REGISTRY_PASSWORD }}
          containerAppName: legal-summarizer-api
          resourceGroup: Legal_Summarizer_NLP
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


